#+TITLE: Emacs Documented Configuration File.
#+OPTIONS: toc:4 h:4

* Basic configuration
** Personal Informations
#+BEGIN_SRC emacs-lisp
(setq user-full-name "Fabien Cesari"
      user-mail-address "fabien.cesari@gmail.com")
#+END_SRC

** No splash screen 
#+BEGIN_SRC emacs-lisp
(setq inhibit-startup-screen t)
#+END_SRC

** System load
#+BEGIN_SRC emacs-lisp
(add-to-list 'load-path "/opt/local/share/emacs/site-lisp")
(add-to-list 'load-path "/usr/share/emacs/site-lisp/elib/")
#+END_SRC

** User Load

#+BEGIN_SRC emacs-lisp
(add-to-list 'load-path "~/.emacs.d/external/jdee-2.4.1/lisp")
(add-to-list 'load-path "~/.emacs.d/external/")
(add-to-list 'load-path "~/.emacs.d/external/git/")
(add-to-list 'load-path "~/.emacs.d/external/muse/lisp")
(add-to-list 'load-path "~/.emacs.d/external/autocomplete/")
(add-to-list 'load-path "~/.emacs.d/external/ruby-mode")
(add-to-list 'load-path "~/.emacs/external/cedet-1.1/common/")
(add-to-list 'load-path "~/.emacs/external/cedet-1.1/contrib/")
(add-to-list 'load-path "~/.emacs.d/external/autocomplete/")
(add-to-list 'load-path "~/.emacs.d/external/nxhtml/util")
(add-to-list 'load-path "~/.emacs.d/external/rhtml")
(add-to-list 'load-path "~/.emacs.d/external/php-mode")
#+END_SRC
   
** Tempo mode: provides a simple way to define powerful templates, or macros
#+BEGIN_SRC emacs-lisp
(load "tempo")
#+END_SRC

** Emacs auto generated 
#+BEGIN_SRC emacs-lisp
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(gdb-max-frames 100)
 '(global-subword-mode t)
 '(ido-enable-flex-matching t)
 '(ido-everywhere t)
 '(ido-mode (quote both) nil (ido))
 '(tool-bar-mode t))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
#+END_SRC

** svn activation.
#+BEGIN_SRC emacs-lisp
(require 'psvn)
#+END_SRC

** git activation
#+BEGIN_SRC emacs-lisp
(require 'git)
#+END_SRC

** windowmove:  Change buffer with shift-arrows
#+BEGIN_SRC emacs-lisp
; change window focus with shift-arrows
;;;; (require 'windmove)
(windmove-default-keybindings)
(setq windmove-wrap-around t)
(require 'buffer-move)
#+END_SRC

** Key Binings
#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-+") 'hs-toggle-hiding)

(add-hook 'c-mode-common-hook   'hs-minor-mode)
(add-hook 'emacs-lisp-mode-hook 'hs-minor-mode)
(add-hook 'java-mode-hook       'hs-minor-mode)
(add-hook 'espresso-mode-hook   'hs-minor-mode)
(add-hook 'lisp-mode-hook       'hs-minor-mode)
(add-hook 'perl-mode-hook       'hs-minor-mode)
(add-hook 'sh-mode-hook         'hs-minor-mode)

(global-set-key (kbd "<C-S-up>")     'buf-move-up)
(global-set-key (kbd "<C-S-donw>")   'buf-move-down)
(global-set-key (kbd "<C-S-left>")   'buf-move-left)
(global-set-key (kbd "<C-S-right>")  'buf-move-right)
#+END_SRC

** ftp configuration with TRAMP (Transparent Remote Access, Multiple Protocols) 
#+BEGIN_SRC emacs-lisp
(require 'tramp)
(setq tramp-default-method "ftp")
#+END_SRC

** Emacs multi-term
#+BEGIN_SRC emacs-lisp
;(require 'multi-term)
;(setq multi-term-program "/bin/zsh")
#+END_SRC


* OS specific configuaration
** OSX keyboard adaptation 
#+BEGIN_SRC emacs-lisp
(setq mac-option-modifier 'none)
(setq mac-command-modifier 'meta)
#+END_SRC
** forget Command-Q to quit, use M-Q to fill-region
#+BEGIN_SRC emacs-lisp
(when (eq system-type 'darwin)
  (setq mac-pass-command-to-system nil) )
#+END_SRC

** system Path
#+BEGIN_SRC emacs-lisp
(setenv "PATH" "/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/Applications/AudioSculpt 3.0.23i/Kernels:/opt/local/bin:/opt/local/sbin:/usr/local/share/python:/Users/cesari/include:/Users/cesari/lib:/Users/cesari/bin:/Applications/MATLAB_R2010b.app/bin")
#+END_SRC
   
   
* External plugins    
** ELPA -- package.el
#+BEGIN_SRC emacs-lisp
(when
    (load
     (expand-file-name "~/.emacs.d/external/package.el"))
  (package-initialize))
#+END_SRC
   
** Doxymacs: Documentation shortcuts:
   C-c d ? will look up documentation for the symbol under the point.
   C-c d r will rescan your Doxygen tags file.
   C-c d f will insert a Doxygen comment for the next function.
   C-c d i will insert a Doxygen comment for the current file.
   C-c d ; will insert a Doxygen comment for a member variable on the current line (like M-;).
   C-c d m will insert a blank multi-line Doxygen comment.
   C-c d s will insert a blank single-line Doxygen comment.
   C-c d @ will insert grouping comments around the current region.

#+BEGIN_SRC emacs-lisp
(load "doxymacs")
(load "xml-parse")
(require 'doxymacs)
(add-hook 'c-mode-common-hook'doxymacs-mode)
(defun my-c-font-lock-doxy-html (limit)
  (while (re-search-forward "<.+?>" limit 'move)
    (let ((beg (match-beginning 0))
          (end (match-end 0)))
      (if (nth 4 (syntax-ppss beg))
          (when (nth 4 (syntax-ppss end))
            (c-put-font-lock-face beg end 'font-lock-keyword-face))
        (goto-char end))))
  nil)
(defun my-c-mode-common-hook ()
  (font-lock-add-keywords nil '((my-c-font-lock-doxy-html))))
(add-hook 'c-mode-common-hook 'my-c-mode-common-hook)
#+END_SRC

** Matlab from emacs
#+BEGIN_SRC emacs-lisp
;;Matlab-emacs config
;; add repo to the pah.
(setq load-path (append load-path(list "~/.emacs.d/external/matlab-emacs")))

(autoload 'matlab-mode "matlab" "Enter MATLAB Mode." t)
(setq auto-mode-alist (cons '("\\.m\\'" . matlab-mode) auto-mode-alist))
(autoload 'matlab-shell "matlab" "Interactive MATLAB mode." t)

;; Customization:
(setq matlab-indent-function t)	; if you want function bodies indented
(setq matlab-verify-on-save-flag nil) ; turn off auto-verify on save
(defun my-matlab-mode-hook ()
  (setq fill-column 76))		; where auto-fill should wrap
(add-hook 'matlab-mode-hook 'my-matlab-mode-hook)
(defun my-matlab-shell-mode-hook ()
  '())
(add-hook 'matlab-shell-mode-hook 'my-matlab-shell-mode-hook)

;; Turn off Matlab desktop
(setq matlab-shell-command-switches '("-nojvm"))
#+END_SRC

** Emacs cedet
#+BEGIN_SRC emacs-lisp
(require 'cedet)
#+END_SRC

** Emacs muse
#+BEGIN_SRC emacs-lisp
(require 'muse-mode)     ; load authoring mode
(require 'muse-html)     ; load publishing styles I use
(require 'muse-latex)
(require 'muse-texinfo)
(require 'muse-docbook)
(require 'muse-project)  ; publish files in projects
#+END_SRC

** nxhtml 
#+BEGIN_SRC emacs-lisp
(load "~/.emacs.d/external/nxhtml/autostart.el")
(setq
      nxhtml-global-minor-mode t
      mumamo-chunk-coloring 'submode-colored
      nxhtml-skip-welcome t
      indent-region-mode t
      rng-nxml-auto-validate-flag nil
      nxml-degraded t)
     (add-to-list 'auto-mode-alist '("\\.html\\.erb\\'" . eruby-nxhtml-mumamo))
#+END_SRC
   
** rhtml mode
#+BEGIN_SRC emacs-lisp
     (require 'rhtml-mode)
     (add-hook 'rhtml-mode-hook
     (lambda () (rinari-launch)))
#+END_SRC
** Autocomplete
#+BEGIN_SRC emacs-lisp
   (require 'auto-complete-config)
   (add-to-list 'ac-dictionary-directories "~/.emacs.d/external/autocomplete//ac-dict")
   (ac-config-default)
#+END_SRC
   
** MuMaMo: Multiple Major Mode, for rhtml files
#+BEGIN_SRC emacs-lisp     
     (require 'mumamo-fun)
     (setq mumamo-chunk-coloring 'submode-colored)
     (add-to-list 'auto-mode-alist '("\\.rhtml\\'" . eruby-html-mumamo))
     (add-to-list 'auto-mode-alist '("\\.html\\.erb\\'" . eruby-html-mumamo))
#+END_SRC
** Ruby mode
#+BEGIN_SRC emacs-lisp
(require 'ruby-mode)
(require 'ruby-style)
(require 'ruby-electric)
(add-hook 'ruby-mode-hook 'ruby-electric-mode)
#+END_SRC
   
** Emacs Rails (in fact rails reloaded)
   #+BEGIN_SRC emacs-lisp      
   ;(setq load-path (cons (expand-file-name "~/.emacs.d/external/emacs-rails") load-path))
   ;(require 'rails-autoload)      
   #+END_SRC
** RINARI - Rinari Is Not A Ruby IDE - Interactively Do Things (highly recommended, but not strictly required)   
   #+BEGIN_SRC emacs-lisp                   
    ;(add-to-list 'load-path "~/.emacs.d/external/rinari")
    ;(require 'rinari)
    ;(setq rinari-tags-file-name "TAGS")
   #+END_SRC

** php Mode. byte compiled.

#+BEGIN_SRC emacs-lisp
(require 'php-mode)
(add-to-list 'auto-mode-alist '("\\.module$" . php-mode))
(add-to-list 'auto-mode-alist '("\\.inc$" . php-mode))
(add-to-list 'auto-mode-alist '("\\.install$" . php-mode))
(add-to-list 'auto-mode-alist '("\\.engine$" . php-mode))
#+END_SRC


   
   
